// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	Password   string             `json:"password"`
	Avatar     pgtype.Text        `json:"avatar"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  time.Time          `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleID    int64     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}
