// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: role.sql

package repository

import (
	"context"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECt id, name, created_at
FROM roles
WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
